import { GenerateV1Input } from '@hautechai/sdk/dist/autogenerated/api';

export type GenerateWidgetIncomingMethodHandlers = {
    downloadImage: (data: { imageId: string }) => Promise<void>;
};

export type GenerateWidgetButton = {
    text?: string;
    visible?: boolean;
};

export type GenerateWidgetProps = {
    buttons?: {
        download?: GenerateWidgetButton;
        retouch?: GenerateWidgetButton;
        upscale?: GenerateWidgetButton;
    };
    collectionId: string;
    input: Partial<GenerateV1Input> & { productImageId: string };
};

export type GenerateWidgetOutcomingMethods = {
    getImages: () => Promise<string[]>;
    setProps: (props: GenerateWidgetProps) => Promise<void>;
    start: () => Promise<void>;
};
